# Generated by Django 5.1.6 on 2025-02-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication2Af',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('document', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField()),
                ('validate_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authentication_2af',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('financialinstitutioncode', models.CharField(db_column='financialInstitutionCode', max_length=255)),
                ('financialinstitutionname', models.CharField(db_column='financialInstitutionName', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'banks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_code', models.CharField(db_comment='Campo que registra el nit de la empresa', max_length=255)),
                ('client_id', models.CharField(db_comment='Campo que registra el codigo del cliente dado por ach', max_length=255)),
                ('client_secret', models.CharField(db_comment='Campo que registra codigo secreto dado por ach', max_length=255)),
                ('entity_name', models.CharField(db_comment='Nombre de la entidad.', max_length=255)),
                ('type_entity', models.CharField(db_comment='Tipo de entidad 01 para natural, 02 para juridica', max_length=255)),
                ('type_document', models.CharField(db_comment='Tipo de documento en este caso NIT.', max_length=255)),
                ('number_document', models.CharField(db_comment='Numero de nit', max_length=255)),
                ('ciiu', models.CharField(db_comment='Codigo ciiu referenciado por el dane.', max_length=255)),
                ('encryption_key', models.CharField(db_comment='Llave de cifrado simetrico AES 256 bits', max_length=255)),
                ('iv_key', models.CharField(db_comment='IV de cifrado simetrico AES 256 bits', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogErrorPays',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(db_comment='Documento del cliente.', max_length=255)),
                ('obligation', models.CharField(db_comment='Obligacion del cliente.', max_length=255)),
                ('cartera', models.CharField(db_comment='Key de la cartera donde esta la deuda.', max_length=255)),
                ('trazabilitycode', models.IntegerField(db_column='trazabilityCode', db_comment='Codigo de la transaccion.')),
                ('errors', models.JSONField(db_comment='Json que almacena los errores.')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_error_pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogResponses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('request_parameters', models.JSONField(db_comment='campo que guarda toda la data de la peticion')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_responses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=255)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoSupportedCarteras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_cartera', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'no_supported_carteras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(db_comment='Campo que registra el documento del cliente.', max_length=255)),
                ('obligation', models.CharField(db_comment='Campo que registra el numero de obligacion que pagaron', max_length=255)),
                ('transaction_state', models.CharField(blank=True, db_comment='Campo que registra el estado de la transaccion', max_length=255, null=True)),
                ('authorization_id', models.CharField(blank=True, db_comment='Campo que registra el numero de autorizacion', max_length=255, null=True)),
                ('amount_pay', models.CharField(db_comment='Campo que registra monto pagado', max_length=255)),
                ('key_cartera', models.CharField(db_comment='Campo que registra monto pagado', max_length=255)),
                ('trazabilitycode', models.CharField(db_column='trazabilityCode', db_comment='Codigo de la transaccion.', max_length=255, unique=True)),
                ('payment_applied', models.IntegerField(db_comment='Campo que registra si ya se aplico el pago a la cartera')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(db_comment='Nombre del banco de la cartera donde se aplica el pago.', max_length=255)),
                ('agreement', models.CharField(db_comment='Convenio del banco', max_length=255)),
                ('method', models.CharField(db_comment='Metodo de pago', max_length=255)),
                ('ticketid', models.CharField(db_column='ticketId', db_comment='Numero de factura que se genera para el pago.', max_length=255)),
                ('format', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessTokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tokenable_type', models.CharField(max_length=255)),
                ('tokenable_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_access_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secret2Af',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('secret_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secret_2af',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_code', models.CharField(max_length=255)),
                ('account', models.CharField(db_comment='Cuenta relacionada al codigo de servicio', max_length=255)),
                ('type_account', models.CharField(db_comment='Tipo de cuenta', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('seconds', models.CharField(max_length=255)),
                ('generation_date', models.DateField()),
                ('generation_hour', models.TimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.IntegerField(blank=True, db_comment='Campo de Identificacion de empresa', null=True)),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDocuments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'type_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'type_users',
                'managed': False,
            },
        ),
    ]
